title: 青年晚报
subtitle: Youth Evening Post
description: 一个三十岁人的个人刊物
baseurl: "/home"
url: "https://3egirlsdream.github.io"

permalink: /:title.html
timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

excerpt_separator: "\n\n"

plugins:
  - jekyll-paginate

paginate: 12
paginate_path: "/posts/page:num"

collections:
  posts:
    title: Posts
    output: true
